/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AccessToken {
  #[serde(rename = "name")]
  name: String
}

impl AccessToken {
  pub fn new(name: String) -> AccessToken {
    AccessToken {
      name: name
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> AccessToken {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


}



