/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AddTimeOption : AddTimeOption options for adding time to an issue

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AddTimeOption {
  /// time in seconds
  #[serde(rename = "time")]
  time: i64
}

impl AddTimeOption {
  /// AddTimeOption options for adding time to an issue
  pub fn new(time: i64) -> AddTimeOption {
    AddTimeOption {
      time: time
    }
  }

  pub fn set_time(&mut self, time: i64) {
    self.time = time;
  }

  pub fn with_time(mut self, time: i64) -> AddTimeOption {
    self.time = time;
    self
  }

  pub fn time(&self) -> &i64 {
    &self.time
  }


}



