/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Commit {
  #[serde(rename = "author")]
  author: Option<::models::User>,
  #[serde(rename = "commit")]
  commit: Option<::models::RepoCommit>,
  #[serde(rename = "committer")]
  committer: Option<::models::User>,
  #[serde(rename = "html_url")]
  html_url: Option<String>,
  #[serde(rename = "parents")]
  parents: Option<Vec<::models::CommitMeta>>,
  #[serde(rename = "sha")]
  sha: Option<String>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl Commit {
  pub fn new() -> Commit {
    Commit {
      author: None,
      commit: None,
      committer: None,
      html_url: None,
      parents: None,
      sha: None,
      url: None
    }
  }

  pub fn set_author(&mut self, author: ::models::User) {
    self.author = Some(author);
  }

  pub fn with_author(mut self, author: ::models::User) -> Commit {
    self.author = Some(author);
    self
  }

  pub fn author(&self) -> Option<&::models::User> {
    self.author.as_ref()
  }

  pub fn reset_author(&mut self) {
    self.author = None;
  }

  pub fn set_commit(&mut self, commit: ::models::RepoCommit) {
    self.commit = Some(commit);
  }

  pub fn with_commit(mut self, commit: ::models::RepoCommit) -> Commit {
    self.commit = Some(commit);
    self
  }

  pub fn commit(&self) -> Option<&::models::RepoCommit> {
    self.commit.as_ref()
  }

  pub fn reset_commit(&mut self) {
    self.commit = None;
  }

  pub fn set_committer(&mut self, committer: ::models::User) {
    self.committer = Some(committer);
  }

  pub fn with_committer(mut self, committer: ::models::User) -> Commit {
    self.committer = Some(committer);
    self
  }

  pub fn committer(&self) -> Option<&::models::User> {
    self.committer.as_ref()
  }

  pub fn reset_committer(&mut self) {
    self.committer = None;
  }

  pub fn set_html_url(&mut self, html_url: String) {
    self.html_url = Some(html_url);
  }

  pub fn with_html_url(mut self, html_url: String) -> Commit {
    self.html_url = Some(html_url);
    self
  }

  pub fn html_url(&self) -> Option<&String> {
    self.html_url.as_ref()
  }

  pub fn reset_html_url(&mut self) {
    self.html_url = None;
  }

  pub fn set_parents(&mut self, parents: Vec<::models::CommitMeta>) {
    self.parents = Some(parents);
  }

  pub fn with_parents(mut self, parents: Vec<::models::CommitMeta>) -> Commit {
    self.parents = Some(parents);
    self
  }

  pub fn parents(&self) -> Option<&Vec<::models::CommitMeta>> {
    self.parents.as_ref()
  }

  pub fn reset_parents(&mut self) {
    self.parents = None;
  }

  pub fn set_sha(&mut self, sha: String) {
    self.sha = Some(sha);
  }

  pub fn with_sha(mut self, sha: String) -> Commit {
    self.sha = Some(sha);
    self
  }

  pub fn sha(&self) -> Option<&String> {
    self.sha.as_ref()
  }

  pub fn reset_sha(&mut self) {
    self.sha = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> Commit {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



