/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateEmailOption : CreateEmailOption options when creating email addresses

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateEmailOption {
  /// email addresses to add
  #[serde(rename = "emails")]
  emails: Option<Vec<String>>
}

impl CreateEmailOption {
  /// CreateEmailOption options when creating email addresses
  pub fn new() -> CreateEmailOption {
    CreateEmailOption {
      emails: None
    }
  }

  pub fn set_emails(&mut self, emails: Vec<String>) {
    self.emails = Some(emails);
  }

  pub fn with_emails(mut self, emails: Vec<String>) -> CreateEmailOption {
    self.emails = Some(emails);
    self
  }

  pub fn emails(&self) -> Option<&Vec<String>> {
    self.emails.as_ref()
  }

  pub fn reset_emails(&mut self) {
    self.emails = None;
  }

}



