/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// EditGitHookOption : EditGitHookOption options when modifying one Git hook

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EditGitHookOption {
  #[serde(rename = "content")]
  content: Option<String>
}

impl EditGitHookOption {
  /// EditGitHookOption options when modifying one Git hook
  pub fn new() -> EditGitHookOption {
    EditGitHookOption {
      content: None
    }
  }

  pub fn set_content(&mut self, content: String) {
    self.content = Some(content);
  }

  pub fn with_content(mut self, content: String) -> EditGitHookOption {
    self.content = Some(content);
    self
  }

  pub fn content(&self) -> Option<&String> {
    self.content.as_ref()
  }

  pub fn reset_content(&mut self) {
    self.content = None;
  }

}



