/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// EditDeadlineOption : EditDeadlineOption options for creating a deadline

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EditDeadlineOption {
  #[serde(rename = "due_date")]
  due_date: String
}

impl EditDeadlineOption {
  /// EditDeadlineOption options for creating a deadline
  pub fn new(due_date: String) -> EditDeadlineOption {
    EditDeadlineOption {
      due_date: due_date
    }
  }

  pub fn set_due_date(&mut self, due_date: String) {
    self.due_date = due_date;
  }

  pub fn with_due_date(mut self, due_date: String) -> EditDeadlineOption {
    self.due_date = due_date;
    self
  }

  pub fn due_date(&self) -> &String {
    &self.due_date
  }


}



