/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FileCommitResponse {
  #[serde(rename = "author")]
  author: Option<::models::CommitUser>,
  #[serde(rename = "committer")]
  committer: Option<::models::CommitUser>,
  #[serde(rename = "html_url")]
  html_url: Option<String>,
  #[serde(rename = "message")]
  message: Option<String>,
  #[serde(rename = "parents")]
  parents: Option<Vec<::models::CommitMeta>>,
  #[serde(rename = "sha")]
  sha: Option<String>,
  #[serde(rename = "tree")]
  tree: Option<::models::CommitMeta>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl FileCommitResponse {
  pub fn new() -> FileCommitResponse {
    FileCommitResponse {
      author: None,
      committer: None,
      html_url: None,
      message: None,
      parents: None,
      sha: None,
      tree: None,
      url: None
    }
  }

  pub fn set_author(&mut self, author: ::models::CommitUser) {
    self.author = Some(author);
  }

  pub fn with_author(mut self, author: ::models::CommitUser) -> FileCommitResponse {
    self.author = Some(author);
    self
  }

  pub fn author(&self) -> Option<&::models::CommitUser> {
    self.author.as_ref()
  }

  pub fn reset_author(&mut self) {
    self.author = None;
  }

  pub fn set_committer(&mut self, committer: ::models::CommitUser) {
    self.committer = Some(committer);
  }

  pub fn with_committer(mut self, committer: ::models::CommitUser) -> FileCommitResponse {
    self.committer = Some(committer);
    self
  }

  pub fn committer(&self) -> Option<&::models::CommitUser> {
    self.committer.as_ref()
  }

  pub fn reset_committer(&mut self) {
    self.committer = None;
  }

  pub fn set_html_url(&mut self, html_url: String) {
    self.html_url = Some(html_url);
  }

  pub fn with_html_url(mut self, html_url: String) -> FileCommitResponse {
    self.html_url = Some(html_url);
    self
  }

  pub fn html_url(&self) -> Option<&String> {
    self.html_url.as_ref()
  }

  pub fn reset_html_url(&mut self) {
    self.html_url = None;
  }

  pub fn set_message(&mut self, message: String) {
    self.message = Some(message);
  }

  pub fn with_message(mut self, message: String) -> FileCommitResponse {
    self.message = Some(message);
    self
  }

  pub fn message(&self) -> Option<&String> {
    self.message.as_ref()
  }

  pub fn reset_message(&mut self) {
    self.message = None;
  }

  pub fn set_parents(&mut self, parents: Vec<::models::CommitMeta>) {
    self.parents = Some(parents);
  }

  pub fn with_parents(mut self, parents: Vec<::models::CommitMeta>) -> FileCommitResponse {
    self.parents = Some(parents);
    self
  }

  pub fn parents(&self) -> Option<&Vec<::models::CommitMeta>> {
    self.parents.as_ref()
  }

  pub fn reset_parents(&mut self) {
    self.parents = None;
  }

  pub fn set_sha(&mut self, sha: String) {
    self.sha = Some(sha);
  }

  pub fn with_sha(mut self, sha: String) -> FileCommitResponse {
    self.sha = Some(sha);
    self
  }

  pub fn sha(&self) -> Option<&String> {
    self.sha.as_ref()
  }

  pub fn reset_sha(&mut self) {
    self.sha = None;
  }

  pub fn set_tree(&mut self, tree: ::models::CommitMeta) {
    self.tree = Some(tree);
  }

  pub fn with_tree(mut self, tree: ::models::CommitMeta) -> FileCommitResponse {
    self.tree = Some(tree);
    self
  }

  pub fn tree(&self) -> Option<&::models::CommitMeta> {
    self.tree.as_ref()
  }

  pub fn reset_tree(&mut self) {
    self.tree = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> FileCommitResponse {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



