/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// IssueDeadline : IssueDeadline represents an issue deadline

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IssueDeadline {
  #[serde(rename = "due_date")]
  due_date: Option<String>
}

impl IssueDeadline {
  /// IssueDeadline represents an issue deadline
  pub fn new() -> IssueDeadline {
    IssueDeadline {
      due_date: None
    }
  }

  pub fn set_due_date(&mut self, due_date: String) {
    self.due_date = Some(due_date);
  }

  pub fn with_due_date(mut self, due_date: String) -> IssueDeadline {
    self.due_date = Some(due_date);
    self
  }

  pub fn due_date(&self) -> Option<&String> {
    self.due_date.as_ref()
  }

  pub fn reset_due_date(&mut self) {
    self.due_date = None;
  }

}



