/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// IssueLabelsOption : IssueLabelsOption a collection of labels

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IssueLabelsOption {
  /// list of label IDs
  #[serde(rename = "labels")]
  labels: Option<Vec<i64>>
}

impl IssueLabelsOption {
  /// IssueLabelsOption a collection of labels
  pub fn new() -> IssueLabelsOption {
    IssueLabelsOption {
      labels: None
    }
  }

  pub fn set_labels(&mut self, labels: Vec<i64>) {
    self.labels = Some(labels);
  }

  pub fn with_labels(mut self, labels: Vec<i64>) -> IssueLabelsOption {
    self.labels = Some(labels);
    self
  }

  pub fn labels(&self) -> Option<&Vec<i64>> {
    self.labels.as_ref()
  }

  pub fn reset_labels(&mut self) {
    self.labels = None;
  }

}



