/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MarkdownOption : MarkdownOption markdown options

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MarkdownOption {
  /// Context to render  in: body
  #[serde(rename = "Context")]
  context: Option<String>,
  /// Mode to render  in: body
  #[serde(rename = "Mode")]
  mode: Option<String>,
  /// Text markdown to render  in: body
  #[serde(rename = "Text")]
  text: Option<String>,
  /// Is it a wiki page ?  in: body
  #[serde(rename = "Wiki")]
  wiki: Option<bool>
}

impl MarkdownOption {
  /// MarkdownOption markdown options
  pub fn new() -> MarkdownOption {
    MarkdownOption {
      context: None,
      mode: None,
      text: None,
      wiki: None
    }
  }

  pub fn set_context(&mut self, context: String) {
    self.context = Some(context);
  }

  pub fn with_context(mut self, context: String) -> MarkdownOption {
    self.context = Some(context);
    self
  }

  pub fn context(&self) -> Option<&String> {
    self.context.as_ref()
  }

  pub fn reset_context(&mut self) {
    self.context = None;
  }

  pub fn set_mode(&mut self, mode: String) {
    self.mode = Some(mode);
  }

  pub fn with_mode(mut self, mode: String) -> MarkdownOption {
    self.mode = Some(mode);
    self
  }

  pub fn mode(&self) -> Option<&String> {
    self.mode.as_ref()
  }

  pub fn reset_mode(&mut self) {
    self.mode = None;
  }

  pub fn set_text(&mut self, text: String) {
    self.text = Some(text);
  }

  pub fn with_text(mut self, text: String) -> MarkdownOption {
    self.text = Some(text);
    self
  }

  pub fn text(&self) -> Option<&String> {
    self.text.as_ref()
  }

  pub fn reset_text(&mut self) {
    self.text = None;
  }

  pub fn set_wiki(&mut self, wiki: bool) {
    self.wiki = Some(wiki);
  }

  pub fn with_wiki(mut self, wiki: bool) -> MarkdownOption {
    self.wiki = Some(wiki);
    self
  }

  pub fn wiki(&self) -> Option<&bool> {
    self.wiki.as_ref()
  }

  pub fn reset_wiki(&mut self) {
    self.wiki = None;
  }

}



