/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MergePullRequestOption : MergePullRequestForm form for merging Pull Request

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MergePullRequestOption {
  #[serde(rename = "Do")]
  _do: String,
  #[serde(rename = "MergeMessageField")]
  merge_message_field: Option<String>,
  #[serde(rename = "MergeTitleField")]
  merge_title_field: Option<String>
}

impl MergePullRequestOption {
  /// MergePullRequestForm form for merging Pull Request
  pub fn new(_do: String) -> MergePullRequestOption {
    MergePullRequestOption {
      _do: _do,
      merge_message_field: None,
      merge_title_field: None
    }
  }

  pub fn set__do(&mut self, _do: String) {
    self._do = _do;
  }

  pub fn with__do(mut self, _do: String) -> MergePullRequestOption {
    self._do = _do;
    self
  }

  pub fn _do(&self) -> &String {
    &self._do
  }


  pub fn set_merge_message_field(&mut self, merge_message_field: String) {
    self.merge_message_field = Some(merge_message_field);
  }

  pub fn with_merge_message_field(mut self, merge_message_field: String) -> MergePullRequestOption {
    self.merge_message_field = Some(merge_message_field);
    self
  }

  pub fn merge_message_field(&self) -> Option<&String> {
    self.merge_message_field.as_ref()
  }

  pub fn reset_merge_message_field(&mut self) {
    self.merge_message_field = None;
  }

  pub fn set_merge_title_field(&mut self, merge_title_field: String) {
    self.merge_title_field = Some(merge_title_field);
  }

  pub fn with_merge_title_field(mut self, merge_title_field: String) -> MergePullRequestOption {
    self.merge_title_field = Some(merge_title_field);
    self
  }

  pub fn merge_title_field(&self) -> Option<&String> {
    self.merge_title_field.as_ref()
  }

  pub fn reset_merge_title_field(&mut self) {
    self.merge_title_field = None;
  }

}



