/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PublicKey : PublicKey publickey is a user key to push code to repository

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PublicKey {
  #[serde(rename = "created_at")]
  created_at: Option<String>,
  #[serde(rename = "fingerprint")]
  fingerprint: Option<String>,
  #[serde(rename = "id")]
  id: Option<i64>,
  #[serde(rename = "key")]
  key: Option<String>,
  #[serde(rename = "key_type")]
  key_type: Option<String>,
  #[serde(rename = "read_only")]
  read_only: Option<bool>,
  #[serde(rename = "title")]
  title: Option<String>,
  #[serde(rename = "url")]
  url: Option<String>,
  #[serde(rename = "user")]
  user: Option<::models::User>
}

impl PublicKey {
  /// PublicKey publickey is a user key to push code to repository
  pub fn new() -> PublicKey {
    PublicKey {
      created_at: None,
      fingerprint: None,
      id: None,
      key: None,
      key_type: None,
      read_only: None,
      title: None,
      url: None,
      user: None
    }
  }

  pub fn set_created_at(&mut self, created_at: String) {
    self.created_at = Some(created_at);
  }

  pub fn with_created_at(mut self, created_at: String) -> PublicKey {
    self.created_at = Some(created_at);
    self
  }

  pub fn created_at(&self) -> Option<&String> {
    self.created_at.as_ref()
  }

  pub fn reset_created_at(&mut self) {
    self.created_at = None;
  }

  pub fn set_fingerprint(&mut self, fingerprint: String) {
    self.fingerprint = Some(fingerprint);
  }

  pub fn with_fingerprint(mut self, fingerprint: String) -> PublicKey {
    self.fingerprint = Some(fingerprint);
    self
  }

  pub fn fingerprint(&self) -> Option<&String> {
    self.fingerprint.as_ref()
  }

  pub fn reset_fingerprint(&mut self) {
    self.fingerprint = None;
  }

  pub fn set_id(&mut self, id: i64) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i64) -> PublicKey {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i64> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_key(&mut self, key: String) {
    self.key = Some(key);
  }

  pub fn with_key(mut self, key: String) -> PublicKey {
    self.key = Some(key);
    self
  }

  pub fn key(&self) -> Option<&String> {
    self.key.as_ref()
  }

  pub fn reset_key(&mut self) {
    self.key = None;
  }

  pub fn set_key_type(&mut self, key_type: String) {
    self.key_type = Some(key_type);
  }

  pub fn with_key_type(mut self, key_type: String) -> PublicKey {
    self.key_type = Some(key_type);
    self
  }

  pub fn key_type(&self) -> Option<&String> {
    self.key_type.as_ref()
  }

  pub fn reset_key_type(&mut self) {
    self.key_type = None;
  }

  pub fn set_read_only(&mut self, read_only: bool) {
    self.read_only = Some(read_only);
  }

  pub fn with_read_only(mut self, read_only: bool) -> PublicKey {
    self.read_only = Some(read_only);
    self
  }

  pub fn read_only(&self) -> Option<&bool> {
    self.read_only.as_ref()
  }

  pub fn reset_read_only(&mut self) {
    self.read_only = None;
  }

  pub fn set_title(&mut self, title: String) {
    self.title = Some(title);
  }

  pub fn with_title(mut self, title: String) -> PublicKey {
    self.title = Some(title);
    self
  }

  pub fn title(&self) -> Option<&String> {
    self.title.as_ref()
  }

  pub fn reset_title(&mut self) {
    self.title = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> PublicKey {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

  pub fn set_user(&mut self, user: ::models::User) {
    self.user = Some(user);
  }

  pub fn with_user(mut self, user: ::models::User) -> PublicKey {
    self.user = Some(user);
    self
  }

  pub fn user(&self) -> Option<&::models::User> {
    self.user.as_ref()
  }

  pub fn reset_user(&mut self) {
    self.user = None;
  }

}



