/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// StateType : StateType issue state type

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct StateType {
}

impl StateType {
  /// StateType issue state type
  pub fn new() -> StateType {
    StateType {
    }
  }

}



