/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TimeStamp : TimeStamp defines a timestamp

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TimeStamp {
}

impl TimeStamp {
  /// TimeStamp defines a timestamp
  pub fn new() -> TimeStamp {
    TimeStamp {
    }
  }

}



